name: osakel
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.2
  cupertino_icons: ^1.0.8

  # Firebase 依存関係
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^14.1.1

  # 状態管理
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # 地図・UI 依存関係
  google_maps_flutter: ^2.5.3
  google_maps_flutter_android: ^2.6.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  intl: ^0.17.0
  url_launcher: ^6.3.1
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
